### ISSUE TITLE
Topnav của trang web bị ẩn nội dung khi màn hình quá nhỏ

### ISSUE THREAD

**Issue by M-DinhHoangViet** [ThiVuaLayTot/ThiVuaLayTot.github.io#67]
![image](https://github.com/user-attachments/assets/62b00354-0a21-46dd-812e-f4a8d34c9246)

**Comment by dung201000000** [comment]
Để sửa lỗi **Topnav bị ẩn nội dung** khi màn hình quá nhỏ, bạn có thể sử dụng một trong những cách sau để cải thiện khả năng hiển thị của thanh điều hướng (Topnav):

### 1. **Responsive Navigation Menu với Media Queries**
- Sử dụng CSS Media Queries để tạo các điều chỉnh cho thanh điều hướng khi kích thước màn hình thay đổi.

Ví dụ:

```css
/* Mặc định cho màn hình lớn */
.topnav {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.topnav a {
  padding: 14px 20px;
  display: block;
  text-decoration: none;
}

/* Khi màn hình nhỏ hơn 600px */
@media (max-width: 600px) {
  .topnav {
    flex-direction: column; /* Chuyển thành cột dọc */
    align-items: flex-start;
  }

  .topnav a {
    padding: 10px;
    width: 100%; /* Đảm bảo các link trải dài theo chiều rộng */
  }
}
```

### 2. **Sử dụng Menu Icon (Hamburger)**
- Bạn có thể ẩn các liên kết trong thanh điều hướng khi màn hình nhỏ và thay vào đó hiển thị một biểu tượng (hamburger) để mở menu.

Ví dụ:

```html
<div class="topnav">
  <a href="#home">Home</a>
  <a href="#about">About</a>
  <a href="#services">Services</a>
  <a href="#contact">Contact</a>
  <a href="javascript:void(0);" class="icon" onclick="toggleMenu()">☰</a>
</div>
```

```css
/* Mặc định cho màn hình lớn */
.topnav a {
  display: block;
  text-align: center;
  padding: 14px;
}

/* Khi màn hình nhỏ hơn 600px */
@media screen and (max-width: 600px) {
  .topnav a:not(:last-child) {
    display: none; /* Ẩn các liên kết */
  }
  .topnav a.icon {
    display: block; /* Hiển thị icon */
  }
}

@media screen and (max-width: 600px) {
  .topnav.responsive {
    position: relative;
  }
  .topnav.responsive a {
    display: block; /* Hiển thị các liên kết khi nhấn icon */
    text-align: left;
  }
}
```

```javascript
function toggleMenu() {
  var x = document.querySelector(".topnav");
  if (x.className === "topnav") {
    x.className += " responsive";
  } else {
    x.className = "topnav";
  }
}
```

### 3. **Giảm kích thước font và khoảng cách padding**
- Điều chỉnh kích thước font, padding hoặc margin của các thành phần trong thanh điều hướng khi màn hình nhỏ.

```css
@media (max-width: 600px) {
  .topnav a {
    font-size: 12px; /* Giảm kích thước font */
    padding: 10px; /* Giảm padding */
  }
}
```

### Kết hợp
Bạn có thể kết hợp các phương pháp trên để có một thanh điều hướng linh hoạt và tương thích tốt với mọi màn hình.
